//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLegacy
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Label lblCartCount;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.LinkButton btnSignOut;
    }
}
