//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLegacy.Checkout
{
    public partial class CheckoutPage
    {
        protected global::System.Web.UI.WebControls.TextBox txtStreet;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.TextBox txtState;
        protected global::System.Web.UI.WebControls.TextBox txtZip;
        protected global::System.Web.UI.WebControls.TextBox txtCountry;
        protected global::System.Web.UI.WebControls.TextBox txtCardNumber;
        protected global::System.Web.UI.WebControls.TextBox txtCardHolder;
        protected global::System.Web.UI.WebControls.TextBox txtExpiry;
        protected global::System.Web.UI.WebControls.TextBox txtCVV;
        protected global::System.Web.UI.WebControls.Repeater rptSummary;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
    }
}
