//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLegacy.Catalog
{
    public partial class CatalogPage
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlBrand;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Repeater rptProducts;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlPager;
        protected global::System.Web.UI.WebControls.Label lblPage;
        protected global::System.Web.UI.WebControls.Label lblTotalPages;
        protected global::System.Web.UI.WebControls.HyperLink btnPrev;
        protected global::System.Web.UI.WebControls.HyperLink btnNext;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClearFilters;
    }
}
