//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopLegacy.Catalog
{
    public partial class ProductDetailPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlProduct;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblBreadcrumb;
        protected global::System.Web.UI.WebControls.Label lblName;
        protected global::System.Web.UI.WebControls.Label lblBrand;
        protected global::System.Web.UI.WebControls.Label lblType;
        protected global::System.Web.UI.WebControls.Label lblPrice;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblStock;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgProduct;
        protected global::System.Web.UI.WebControls.TextBox txtQty;
        protected global::System.Web.UI.WebControls.Button btnAddToCart;
    }
}
